FROM ubuntu:25.04 
# AS builder

ARG DEBIAN_FRONTEND=noninteractive
ARG SIMULATION=native
ENV SIMULATION=${SIMULATION}
ARG BUILDTYPE=debug
ENV BUILDTYPE=${BUILDTYPE}
ARG OMIT_DEPRECATED=false
ENV OMIT_DEPRECATED=${OMIT_DEPRECATED}
# Change once we deploy multiple daemons for cFS to avoid conflicts
ARG ARANYA_DAEMON_SYNC_LISTEN_PORT=9999
ENV ARANYA_DAEMON_SYNC_LISTEN_PORT=${ARANYA_DAEMON_SYNC_LISTEN_PORT} 

# Rust envs
ARG RUST_TOOLCHAIN=nightly
ENV RUSTUP_HOME=/root/.rustup
ENV CARGO_HOME=/root/.cargo
ENV PATH=/root/.cargo/bin:${PATH}

RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y build-essential git cmake curl && \
  rm -rf /var/lib/apt/lists/*

# Install rustup and a specific toolchain (override with --build-arg RUST_TOOLCHAIN=...)
RUN \
   curl -fsSL https://sh.rustup.rs | sh -s -- -y --no-modify-path --profile minimal --default-toolchain ${RUST_TOOLCHAIN} && \
   rustup toolchain install ${RUST_TOOLCHAIN} && \
   rustup default ${RUST_TOOLCHAIN} && \
   rustc -V && cargo -V

# Install aranya-daemon bin
RUN \
   cargo install --git https://github.com/matcala/aranya.git \
    --branch main aranya-daemon \
    --version 3.0.0 \
    --target aarch64-unknown-linux-gnu  \
    --features aqc,experimental,afc,preview \
    && mkdir -m 0755 -p /run/aranya/run /run/aranya/config /run/aranya/logs /run/aranya/cache /run/aranya/state /etc/aranya


# Copy cfs-daemon state in dest dir
COPY ./aranya/cfs-daemon /run/aranya/   
# Copy sample daemon config
# WARNING Change once we deploy multiple daemons for cFS to avoid conflicts 
COPY ./aranya/daemon-config.toml /etc/aranya/daemon-config.toml


WORKDIR /cfs

# Add alias for full build process
RUN echo 'alias rebuild-clean="make distclean && make prep && make && make install"' >> /root/.bashrc
RUN echo 'alias rebuild="make && make install"' >> /root/.bashrc
RUN echo 'alias run="cd /cfs/build/exe/cpu1 && ./core-cpu1"' >> /root/.bashrc

ENTRYPOINT ["/bin/bash", "-c", "aranya-daemon --config /etc/aranya/daemon-config.toml & exec /bin/bash"]
