#ifndef _ARANYA_EP_INTERNAL_CFG_H_
#define _ARANYA_EP_INTERNAL_CFG_H_

#define ARANYA_EP_PIPE_DEPTH 32
#define ARANYA_EP_PIPE_NAME  "ARANYA_EP_CMD_PIPE"

#define ARANYA_EP_NUMBER_OF_TABLES 1

#define ARANYA_EP_TBL_ELEMENT_1_MAX 10

#define ARANYA_EP_TABLE_OUT_OF_RANGE_ERR_CODE -1

#endif